#!/usr/bin/env python3
"""Generate web-sized derivatives + the Jekyll data manifest for /photos.

Full-resolution originals live OUTSIDE the repo (they total ~1 GB, which would
blow past GitHub Pages' limits). Only the derivatives below are committed.

    python3 scripts/build_gallery.py                  # rebuild everything
    python3 scripts/build_gallery.py --skip-existing  # only new photos

Reads:  <ORIGINALS>/*.jpg
Writes: files/wildlife-nature/web/thumb/<slug>.jpg   long edge 600px,  q78
        files/wildlife-nature/web/large/<slug>.jpg   long edge 2000px, q82
        _data/gallery.yml                            slug, width, height

To add photos: drop them in ORIGINALS, rerun with --skip-existing, commit.
"""

import random
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps

SITE = Path(__file__).resolve().parent.parent
# Originals are kept out of the repo; override with a first positional argument.
ORIGINALS = Path(sys.argv[1]) if len(sys.argv) > 1 and not sys.argv[1].startswith("-") \
    else SITE.parent / "wildlife-nature-originals"
SRC = ORIGINALS
WEB = SITE / "files" / "wildlife-nature" / "web"
THUMB_DIR = WEB / "thumb"
LARGE_DIR = WEB / "large"
MANIFEST = SITE / "_data" / "gallery.yml"

THUMB_EDGE = 600
LARGE_EDGE = 2000
THUMB_Q = 78
LARGE_Q = 82

# Pass --skip-existing to rebuild only the manifest, reusing derivatives on disk.
SKIP_EXISTING = "--skip-existing" in sys.argv

# Bump to reshuffle the gallery into a different fixed order.
SHUFFLE_SEED = 20260801


def slugify(stem: str) -> str:
    s = stem.lower().replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return re.sub(r"-{2,}", "-", s).strip("-")


def save_resized(img: Image.Image, edge: int, dest: Path, quality: int):
    out = img.copy()
    out.thumbnail((edge, edge), Image.LANCZOS)
    if out.mode != "RGB":
        out = out.convert("RGB")
    dest.parent.mkdir(parents=True, exist_ok=True)
    out.save(dest, "JPEG", quality=quality, optimize=True, progressive=True)
    return out.size


def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    sources = sorted(p for p in SRC.iterdir()
                     if p.is_file() and p.suffix.lower() in {".jpg", ".jpeg"})
    if not sources:
        sys.exit(f"no source images found in {SRC}")

    records = []
    seen_slugs = {}

    for i, path in enumerate(sources, 1):
        slug = slugify(path.stem)
        if slug in seen_slugs:
            seen_slugs[slug] += 1
            slug = f"{slug}-{seen_slugs[slug]}"
        else:
            seen_slugs[slug] = 1

        large_out = LARGE_DIR / f"{slug}.jpg"
        thumb_out = THUMB_DIR / f"{slug}.jpg"
        with Image.open(path) as img:
            if SKIP_EXISTING and large_out.exists() and thumb_out.exists():
                with Image.open(large_out) as done:
                    w, h = done.size
            else:
                # Honour the EXIF orientation flag so portraits stay portrait.
                img = ImageOps.exif_transpose(img)
                w, h = save_resized(img, LARGE_EDGE, large_out, LARGE_Q)
                save_resized(img, THUMB_EDGE, thumb_out, THUMB_Q)

        records.append({
            "slug": slug,
            "source": path.name,
            "width": w,
            "height": h,
        })
        print(f"[{i:3}/{len(sources)}] {path.name} -> {slug}.jpg ({w}x{h})")

    # Shuffled, not chronological: EXIF dates here are batch-export timestamps
    # (31 files share one second-level date), so they say nothing about capture
    # date. Fixed seed keeps the order stable across rebuilds.
    random.Random(SHUFFLE_SEED).shuffle(records)

    lines = [
        "# Generated by build_gallery.py -- do not edit by hand.",
        "# Add a `caption:` line to any entry; the gallery page will render it.",
    ]
    for r in records:
        # Always quoted: a slug like "007" would otherwise be read as octal 7.
        lines.append(f"- slug: {yaml_quote(r['slug'])}")
        lines.append(f"  width: {r['width']}")
        lines.append(f"  height: {r['height']}")
        lines.append(f"  source: {yaml_quote(r['source'])}")

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text("\n".join(lines) + "\n")

    thumb_bytes = sum(p.stat().st_size for p in THUMB_DIR.glob("*.jpg"))
    large_bytes = sum(p.stat().st_size for p in LARGE_DIR.glob("*.jpg"))
    print(f"\n{len(records)} images")
    print(f"thumbs: {thumb_bytes / 1e6:.1f} MB   large: {large_bytes / 1e6:.1f} MB")
    print(f"manifest: {MANIFEST}")


if __name__ == "__main__":
    main()
